version: "3"

services:    
  mongo:
    image: mongo
    restart: always
    networks:
      - node-webapp-network
  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  node-webapp-network:
    driver: bridge